twilio/twilio-python

twilio/rest/resources/base.py

Don't prepend the error code to the exception message attribute

---

docs/usage/taskrouter.rst

Without workflow_sid, this sample does not work.

fix tasks().create sample to include workflow_sid

---

tests/test_base_resource.py
twilio/rest/resources/base.py

Fixes #219, not sure if the test is needed but I threw it in there

Remove call to count on list resource

---

requirements.txt
tests/test_access_token.py
tests/test_keys.py
tests/test_make_request.py
twilio/access_token.py

Add support for 2.6, 3.2, 3.3, 3.4

Fix edge build

---

twilio/rest/resources/phone_numbers.py

Change near_lat_long to be formatted string

---

tests/test_recordings.py
twilio/rest/resources/recordings.py

Add before and after date param support to Recordings iter method

---

twilio/rest/trunking.py

- Removed the "Trunks" from the trunk base uri

Fix for Broken Trunking helper library

---

tests/ip_messaging/test_channels.py
tests/ip_messaging/test_credentials.py
tests/ip_messaging/test_members.py
tests/ip_messaging/test_messages.py
tests/ip_messaging/test_roles.py
tests/ip_messaging/test_services.py
tests/ip_messaging/test_users.py
twilio/rest/__init__.py
twilio/rest/resources/ip_messaging/channels.py
twilio/rest/resources/ip_messaging/credentials.py
twilio/rest/resources/ip_messaging/members.py
twilio/rest/resources/ip_messaging/messages.py
twilio/rest/resources/ip_messaging/roles.py
twilio/rest/resources/ip_messaging/services.py
twilio/rest/resources/ip_messaging/users.py

- update calls
- Tests are also updated

Fixed issues with ipmessaging

---

tests/ip_messaging/test_channels.py
tests/ip_messaging/test_messages.py
tests/ip_messaging/test_users.py
tests/resources/ip_messaging/channel_instance.json
twilio/rest/resources/ip_messaging/channels.py
twilio/rest/resources/ip_messaging/messages.py
twilio/rest/resources/ip_messaging/users.py

- Channel - Unique Name Parameter
- Message - Update Message
- Users - Corrected the parameter name

Ip messaging updates

---

twilio/rest/client.py

There is missing "addresses" endpoint in client.py.

Added missing "addresses" endpoint to client.py

---

tests/requirements.txt
tests/unit/http/test_validation_client.py
tests/unit/jwt/test_client_validation.py
twilio/http/http_client.py
twilio/http/validation_client.py
twilio/jwt/validation/__init__.py

Still need to smoke test this.

ValidationClient for client validation, add ClientValidationJwt

---

twilio/twiml/voice_response.py

Gather accepts **kwargs as an argument but does not include it when calling self.append so kwargs are dropped, this commit adds kwargs

Adds support for kwargs for <Gather> generation

---

twilio/twiml/messaging_response.py
twilio/twiml/voice_response.py

Issue 341:  Update return values for TwiML code.

---

tests/unit/twiml/test_messaging_response.py
tests/unit/twiml/test_voice_response.py
twilio/twiml/__init__.py
twilio/twiml/messaging_response.py
twilio/twiml/voice_response.py

Support nesting TwiML verbs via `with`

---

tests/unit/test_request_validator.py
twilio/request_validator.py

this pull request is to address issue #392

update request validator to remove port numbers from https urls

---

twilio/http/http_client.py
twilio/http/request.py
twilio/rest/__init__.py

PR adds request/response logging and request hooks to TwilioHttpClient

add request logging and hooking

---

.travis.yml
Makefile

Tested in my fork, seems to be working now.

Fix all Docker image build and push issues

---

twilio/twiml/__init__.py

Adds two new attributes to the overrides.

Override generated attributes when generating TwiML

---

.travis.yml

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

Add py37 to TravisCI config

---

.travis.yml

Auto-deploy via Travis CI upon tagged commit to master

---

twilio/rest/lookups/v1/phone_number.py
twilio/rest/trunking/v1/trunk/phone_number.py

Update a few property types in the lookups and trunking responses

---

MANIFEST.in

Include the license file when packaging the library

---

CONTRIBUTING.md
README.md

chore: update GitHub branch references to use HEAD

---

README.md

fixed #535
added documentation for resolving path length limiting install error on windows.

docs: add path limit error for windows

---

.github/workflows/test-and-deploy.yml
Makefile

Added sonarcloud integration to the github action.

Add sonarcloud integration

---

tests/requirements.txt

chore: add jinja2 for make docs

---

tests/unit/rest/test_client.py

Internal Jira link: [DI-2164](https://issues.corp.twilio.com/browse/DI-2164)

fix: useragent regrex unit test for RC branch

---

twilio/rest/api/__init__.py

[DI-2456](https://issues.corp.twilio.com/browse/DI-2456)

chore: keep v2010 shortcuts

---

.github/workflows/test-and-deploy.yml
Makefile
tests/cluster/test_cluster.py
tests/cluster/test_webhook.py
tests/requirements.txt
twilio/jwt/access_token/grants.py

[DI-2459](https://issues.corp.twilio.com/browse/DI-2459)

test: Adding python cluster tests

---

UPGRADE.md

[DI-2538](https://issues.corp.twilio.com/browse/DI-2538)

docs: Add upgrade guide for 8.0.0-rc

---

UPGRADE.md

Updates the UPGRADE.md doc to provide docs links to relevant resources for changes that could be confusing to customers. Fixes markdownlint warnings.

docs: update UPGRADE.md to include resource links for Voice TwiML changes; apply markdownlint

---

README.md
twilio/rest/__init__.py

fixes #545 
Internal JIRA: [DI-2549](https://issues.corp.twilio.com/browse/DI-2549)
Related PR: https://code.hq.twilio.com/twilio/librarian/pull/494

fix: Update README / docstring for Authenticating Client

---

twilio/rest/intelligence/__init__.py

fix: Create __init__.py for intelligence domain

---

tests/cluster/test_webhook.py

Adding a time delay between creation of the flow and fetching the flow for execution

test: Update test_webhook.py

---

twilio/http/validation_client.py

Update ValidateSslCertificate method in accordance with recent changes to the security testing method

fix: Update ValidateSslCertificate method 

---

requirements.txt

Downgraded aiohttp version to 3.8.4

fix: Requirement changes

---

requirements.txt

Addressing the dependabot alert #732, bumping the aiohttp version from 3.8.5 to 3.8.6

chore: bumping aiohttp from 3.8.5 to 3.8.6

---

.github/workflows/test-and-deploy.yml
requirements.txt

Bump aiohttp to support python 3.12

chore: bump aiohttp

---

.github/workflows/test-and-deploy.yml
requirements.txt

chore: upgrade to python 3.12

---

tests/cluster/test_webhook.py

Removing the webhook test due to ngrok issue, will replace with an alternative

chore: removing webhook test

---

.github/workflows/test-and-deploy.yml

* chore: disable cluster test
* chore: run prettier

chore: disable cluster test (#758)

---

.github/workflows/test-and-deploy.yml

chore: disables cluster test

---

CHANGES.md
UPGRADE.md
tests/unit/http/test_http_client.py

feat!: MVR release preparation

---

twilio/rest/preview/__init__.py

Removing static references of preview.understand api

chore: removing preview.understand references

---

twilio/base/client_base.py

ContentType is required in POST and PUT methods. Adding the support for PUT.

chore: adding contentType in post and put

---

twilio/rest/marketplace/__init__.py

chore: add init file

---

setup.cfg

License scanning tools (such as the one used by GitLab) rely on the project metadata (made available via the PyPi API) to detect the license for a package.
Currently, `license: null` is returned.
This PR adds the license to the project metadata.

chore: add license identifier to project metadata

---

README.md
examples/organization_api.py
examples/public_oauth.py
twilio/credential/client_credential_provider.py
twilio/http/client_token_manager.py

feat: Docs update and examples for organization api uptake and public oauth

---

twilio/rest/preview_iam/__init__.py

fix: Fixing init file for preview iam domain

---

.github/workflows/test-and-deploy.yml

Python 3.7 has EOL and hence is no more available for testing [here](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json). So removing its test.

chore: remove test for 3.7

---

.github/ISSUE_TEMPLATE/bug_report.yml

Added bug report issue template

chore: created bug report issue template

---

requirements.txt
setup.py
tests/unit/http/test_async_http_client.py

Enabling support to the latest aiohttp-retry versions

chore: enable newer versions of aiohttp-retry

---

.github/workflows/test-and-deploy.yml
tests/cluster/test_cluster.py
twilio/rest/assistants/__init__.py

fix: AssistantsBase import

---

UPGRADE.md

feat!: Update UPGRADE.md

---

examples/organization_api.py
examples/public_oauth.py

Fixing the syntax error in oauth example files

chore: fix oauth examples

---

twilio/http/client_token_manager.py
twilio/http/orgs_token_manager.py

chore: update iam token endpoint

---

.github/workflows/test-and-deploy.yml
README.md
setup.py

chore: support Python 3.13

---

twilio/http/client_token_manager.py
twilio/http/orgs_token_manager.py

Changing token endpoint to oauth.twilio.com and using endpoint v2/token.
Similar to #862 

chore: change oauth token endpoint
