docs/usage/usage.rst, tests/task_router/test_activities.py, tests/task_router/test_capability.py, tests/task_router/test_events.py, tests/task_router/test_reservations.py, tests/task_router/test_statistics.py, tests/task_router/test_task_queues.py, tests/task_router/test_tasks.py, tests/task_router/test_workers.py, tests/task_router/test_workflows.py, tests/task_router/test_workspaces.py, tests/test_client.py, tests/test_rest.py.inactive, twilio/rest/__init__.py, twilio/rest/exceptions.py, twilio/rest/resources/base.py
Unfortunately we're still stuck on python 2.6 and twilio-python 3.7.0 introduced several python 2.7isms. This pull request changes those so they work on 2.6.
(crossbar-taskmgr)zwhite-mn4:twilio-python zwhite$ nosetests tests/
...................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 323 tests in 0.218s
OK
=> Fixes for python 2.6

tests/task_router/test_capability.py, tests/task_router/test_task_router_capability.py, tests/task_router/test_task_router_worker_capability.py, twilio/task_router/__init__.py
- Allow fetching Reservations under a Worker by default
- Allow updating Reservations under a Worker
=> Loading Reservations under a Worker by default in TaskRouter JS SDK

twilio/rest/resources/messages.py
I ran into this when trying to find the actual field name in the SDK for `MessagingServiceSid` that the [docs](https://www.twilio.com/docs/api/rest/sending-messages) reference. It seems to be a typo from copying and pasting `calls.py`. :smiley:
=> Fix phone call -> message copypasta

docs/usage/twiml.rst
The closing tag for <Response> in the sample text is missing the slash. e.g. </Response>
=> Fix the closing tag for <response>

tests/test_messages.py, twilio/rest/resources/messages.py
Added the `iter` function to the messages resource which allows
the user to specify `DateSent<` and `DateSent>` parameters.
=> Add iter function to messages resource

setup.py
Without excluding the `tests` folder it gets installed with the library and might (will) cause name collisions for consumers
=> docs and tests shouldnt be packaged and installed with the Twillio lib

.travis.yml, Makefile, setup.py, tests/unit/http/test_http_client.py, tests/unit/http/test_validation_client.py, tests/unit/twiml/test_voice_response.py, tox.ini, twilio/http/http_client.py, twilio/http/validation_client.py, twilio/jwt/access_token/grants.py, twilio/twiml/voice_response.py
* Fixes VoiceResponse.conference does not pass on the `muted` parameter
* Fixes Travis-CI to properly run tests using correct version of Python
* Fixes tests to support both Python 2 and Python 3
* Drops Python 2.6 support (**Breaking Change**)
=> Voice response devx5021 and Python testing, compatibility

tests/unit/http/test_http_client.py, tests/unit/http/test_validation_client.py, twilio/base/page.py, twilio/base/version.py, twilio/http/http_client.py, twilio/http/response.py, twilio/http/validation_client.py
`json.loads` only accepts `str` types in Python >3 and <3.6, so this PR converts all returned `response.content` objects to `str` from `bytes`.
Fixes #358 
Fixes #359
=> Fix broken Python 3.3, 3.4, and 3.5

setup.py, twilio/__init__.py
This PR fixes package distribution, so `twilio-python` installs the correct dependencies based on the Python version it will be running on.
=> Fix package distribution

setup.py, twilio/jwt/__init__.py
Hello. I took the time to trace the following error (caused with PyJWT >= 1.5.1).
This is the same error that resulted in [this being committed](https://github.com/twilio/twilio-python/commit/ae13a244ef0e7059c325533b4cd8fb8c0af5b274).
I **was able** to find out the cause for the exception raised, and **fix the test**.
~**_Also,_ this fix is probably not backwards compatible for PyJWT.**
As I don't use PyJWT, I can't really come up with that myself easily.
All I can come up with is checking pyjwt's version and deciding what call arguments to use according to that.~
**Edit**: So, it is backwards compatible :)
Disclaimer: I don't actually use twilio or this package. Just thought this might help.
***
```
ERROR: test_decode_allows_skip_verification (tests.unit.jwt.test_jwt.JwtTest) …
```
=> PyJWT >= 1.5.1 exception fixed

tests/unit/jwt/test_jwt.py, twilio/jwt/__init__.py, twilio/jwt/access_token/__init__.py, twilio/jwt/client/__init__.py, twilio/jwt/taskrouter/__init__.py
We have had reports that nbf causes problems because if they arent provided they would take the local system time, however since they are validated on twilio's servers that requires that the system that generated the jwt and the system that validates it have relatively synced clocks which cannot be guaranteed.
Nbf will continue to be set if the user passes it on construction.
=> Allow user to turn off nbf generation in jwts

requirements.txt
I was trying to run `make test` and found I needed these dependencies installed into my virtual environment in order to get the tests to run and pass.
=> Add missing dependencies for running tests

tests/unit/jwt/test_access_token.py, twilio/jwt/access_token/grants.py
https://issues.corp.twilio.com/browse/CLIENT-4492
To support JS Clients per this spec:
https://paper.dropbox.com/doc/Proposal-FPA-Token-Format-for-Programmable-Voice-SDKs-xhdFHD6N3aPW9GRp4dXNX
=> Add incoming.allow to AccessToken VoiceGrant

.travis.yml, setup.py
Python 3.3 was EOL-ed on September 29, 2017. This PR removes testing against Python 3.3, as Travis also no longer supports Python 3.3 correctly.
=> Remove Python 3.3 support

tests/unit/http/test_validation_client.py, twilio/http/validation_client.py
Add `validate_ssl_certificate` to check whether we can successfully make requests to the endpoint that uses the new SSL certificate
=> Add method to validate ssl certificate

tests/unit/test_request_validator.py, twilio/request_validator.py
Our internal system sends the bodySHA256 parameter as hex, not base64, so this PR fixes that.
=> Switch body validator to use hex instead of base64

docs/conf.py
Docs were being generated using the current installed version of the lib instead of source path.
> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.
=> Prepend the repo root to the system paths during doc generation

requirements.txt
`requirements.txt` currently uses 1.4.2 as fixed version.
The [setup.py](https://github.com/twilio/twilio-python/blob/c3b38d8ba4db483422c1bd575ce28f7eb6311b33/setup.py#L30) file uses PyJWT >= 1.4.2
It doesn't effect most of the part since, almost all the targets of Makefile
that require installing, do so using `pip install .`
However, docs-install target uses requirements directly but this change
shouldn't break anything in docs.
=> Use PyJWT version >= 1.4.2 in requirements.txt

tests/unit/test_request_validator.py, twilio/request_validator.py
=> added validation of signature without stripping port number

twilio/rest/lookups/v1/phone_number.py
This PR closes #451, where the typehint for `PhoneNumberInstance.carrier` was wrong.
=> Change typehint for `PhoneNumberInstance.carrier`

.travis.yml, setup.py, tox.ini
Python 3.8 is there, so I believe that it would be nice to declare support and add tests for it on CI.
Python 3.8.0 release announcement:
https://discuss.python.org/t/python-3-8-0-is-now-available/2478
=> Declare support for Python 3.8

AUTHORS.md, tests/unit/http/test_http_client.py, twilio/http/http_client.py
Fixes #460 - Adds a timeout parameter to the TwilioHttpClient constructor which is defaulted to None
=> Adding timeout to TwilioHttpClient constructor

README.rst
Official documentation makes no mention of Exceptions being thrown or available.
Document this behavior in the README.
For example, for SMS:
https://www.twilio.com/docs/sms/send-messages
https://www.twilio.com/docs/sms/api/message
These documentation links might lead one to think that errors that occur during the process would be stored in the message object created by the client.messages.create() call (in message.error_code, message.error_message, or message.status).
=> Document exception case in README

twilio/base/obsolete.py
Related to #426 - Do not inherit from `BaseException`
=> fix: Change ObsoleteException to inherit from Exception instead of BaseException

.deepsource.toml, tests/unit/http/test_http_client.py, tests/unit/http/test_validation_client.py, twilio/base/page.py, twilio/base/serialize.py, twilio/jwt/validation/__init__.py, twilio/request_validator.py
Changes:
- Fix dangerous default argument in `twilio/base/serialize.py` (PYL-W0102)
- Classmethods should have `cls` as the first arg. in `twilio/jwt/validation/__init__.py` and `twilio/base/page.py` (PYL-C0202)
- Removed unused imports in `tests/unit/http/test_validation_client.py` and `tests/unit/http/test_http_client.py` (PYL-W0611)
- Fix `len()` used as condition in `twilio/request_validator.py` (PYL-C1801)
---
This PR also adds `.deepsource.toml` configuration file to run continuous static analysis on the repo with [DeepSource](https://deepsource.io). Upon enabling DeepSource, quality and security analysis will be run on every PR to detect 500+ types of problems in the changes — including bug risks, anti-patterns, security vulnerabilities, etc.
DeepSource is a **free to use for …
=> fix: Resolve some bug risks and code quality issues

CONTRIBUTING.md
Fixes https://github.com/twilio/twilio-python/issues/492
=> docs: Add local testing docs

tests/unit/http/test_http_client.py, twilio/http/http_client.py
Ref https://github.com/twilio/twilio-python/issues/409
Adding support for TwilioHttpClient to make requests behind a custom proxy, for example
``` python
from twilio.http.http_client import TwilioHttpClient
from twilio.rest import Client
sid = ''
token = ''
http_client = TwilioHttpClient(proxy={'http': 'http://proxy.twilio.com:8118'})
twilio_client = Client(sid, token, http_client=http_client)
twilio_client.messages.create()
```
=> feat: support http proxy in TwilioHttpClient

twilio/http/http_client.py
Fixes the #506 issue by retrying the failed connection.
I've seen something similar implemented in the Java version: https://github.com/twilio/twilio-java/blob/master/src/main/java/com/twilio/http/HttpClient.java
=> feat: add new max_retries param to TwilioHttpClient

tests/unit/http/test_http_client.py, twilio/base/exceptions.py, twilio/base/version.py
Add a new property named details to RestException. Details is returned by selective apis to populate extra information about errors.
The Studio V2 flow api will be returning extra details with flow validation errors.
=> feat: add details to TwilioRestException

tests/unit/base/test_version.py, twilio/base/version.py
Dropping the page limit calculation since it's no longer used and doesn't make sense to be calculated on a record limit. Also correct the page limit stop logic (with added tests) where an extra page was being queried.
=> fix: drop the page limit calculation and correct the page limit stop condition

twilio/http/http_client.py, twilio/http/response.py
The default HTTP client stores 'Last Request' and 'Last Response' information for access to more data about the raw API request/response. The response object did not contain the headers until now.
=> feat: include API response headers in 'Last Response'

tests/unit/base/test_version.py, twilio/base/version.py
Fetching a BulkExport for a single day returns a `307` with the AWS URL for the file. With this change, the URL will now be included in the response.
Fixes https://github.com/twilio/twilio-python/issues/531
=> fix: allow API redirect responses

requirements.txt
#551
Long term solution would be to support version 2.X (note that this is a breaking change)
=> fix: pin pyjwt dependency

setup.py
Simplifying logic to populate the _version_ in setup.py by moving it to librarian
[Related PR](https://code.hq.twilio.com/twilio/librarian/pull/259)
=> chore: removed file exec to get version

.deepsource.toml, tests/holodeck.py, tests/unit/rest/test_client.py, twilio/rest/__init__.py
Link to JIRA ticket: https://issues.corp.twilio.com/browse/DI-1565
=> chore: update user-agent string to standardize format 

tests/unit/http/test_http_client.py, twilio/http/http_client.py
Feature addition.
This is a followup from https://github.com/twilio/twilio-python/issues/409, where this goes further to allow setting proxy servers using the typical environment variables, as opposed to passing them in via the python interface.
See the docs here:
https://docs.python-requests.org/en/master/user/advanced/
> When you are using the prepared request flow, keep in mind that it does not take into account the environment. This can cause problems if you are using environment variables to change the behaviour of requests. For example: Self-signed SSL certificates specified in REQUESTS_CA_BUNDLE will not be taken into account. As a result an SSL: CERTIFICATE_VERIFY_FAILED is thrown. You can get around this behaviour by explicitly merging the environment settings into your session: …
=> fix: Respect HTTPS_PROXY and other settings from env vars

tests/requirements.txt, tests/unit/test_request_validator.py, twilio/request_validator.py
=> fix: support duplicate query param values

.github/workflows/test-and-deploy.yml
Recent test runs [are failing](https://github.com/twilio/twilio-python/actions/runs/3649444667) due to latest ubuntu images dropping python 3.6. This PR pins an older ubuntu version for python 3.6. We should revert this when we deprecate 3.6.
=> test: Pinning ubuntu version for python 3.6 test runs

.github/workflows/test-and-deploy.yml, README.md, setup.py, tox.ini
=> chore: add support for python 3.11

.github/workflows/test-and-deploy.yml, Dockerfile, Makefile, README.md, setup.py, tox.ini
Jira: [DI-1488](https://issues.corp.twilio.com/browse/DI-1488)
This PR drops support for Python version 3.6. Python 3.7 will be the new required minimum version to use the twilio-python helper library.
=> chore: drop support for python 3.6

requirements.txt, setup.py
`asyncio` is relevant (and distributed) only for Python 3.3 [per PyPI](https://pypi.org/project/asyncio/). Including it after that results in a no-op but fails `pip check`.
=> chore: Drop `asyncio` from requirements

requirements.txt
Adding cython as dependency to support aiohttp wheel creation
Issue: I made changes for java files in twilio oai generator and tests for python are failing - [see logs here](https://github.com/twilio/twilio-oai-generator/actions/runs/6454828737/job/17521145701?pr=527)
https://github.com/twilio/twilio-oai-generator/pull/527
I found the https://github.com/aio-libs/aiohttp/issues/6600#issuecomment-1673948107
=> fix: requirements changes

docs/conf.py
Updating intersphinx_mapping to fix docs [error](https://github.com/twilio/twilio-python/actions/runs/10211733169/job/28253624399#step:8:21). The url https://docs.python.org/ has re-directed to https://docs.python.org/3/. 
The fix is suggested by this [thread](https://github.com/jupyterlab/jupyterlab/issues/14422#issuecomment-1520083065).
=> chore: update intersphinx_mapping

twilio/rest/iam/__init__.py
Add missing static init file into new domain for IAM. 
=> chore: add static init file to iam domain

twilio/rest/assistants/__init__.py, twilio/rest/iam/__init__.py
Adding init file for assistants and correcting Iam
=> chore: add assistants init files

tests/unit/http/test_http_client.py, twilio/http/http_client.py
=> chore: update httpclient

README.md
Adding details about how pagination parameters like `page_size` and `limit` work in different cases.
=> docs: update pagination usage in README.md

examples/public_oauth.py
=> docs: update oauth example
